### ISSUE TITLE
File globs would be nice

### ISSUE THREAD

**Issue by ghost** [bahmutov/rollem#14]
it would be cool if there where file globs for entry dist setups so you can have 

a.js -> a.bundle.js
b.js -> b.bundle.js
c.js -> c.bundle.js

if you want to bundle each file in a folder individually.

**Comment by bahmutov** [comment]
Could you implement them inside the config js file?

**Comment by ghost** [comment]
What do you mean? Like how I think it could look like?

``` javascript
export default [{
  entry: 'src/*.js',
  dest: 'dist/',
  extension: 'bundle',
  treeshake: false
}]
```

**Comment by bahmutov** [comment]
Yup, you can grab the filenames yourself and then make a list of config objects to export https://github.com/bahmutov/rollem#rollemconfigjs

**Comment by ghost** [comment]
ah okay so using that glob.sync stuff to get the files?

**Comment by bahmutov** [comment]
Absolutely!

**Comment by ghost** [comment]
Can you elaborate the example a bit further? Like:

``` javascript
import * as glob from "glob";

const sourceFolder = "src";
const distFolder = "dist";
const srcFiles = glob.sync(`${sourceFolder}/*.js`);

export default srcFiles.map(file => {
    var distRegex = new RegExp(`^${sourceFolder}`);
    return {
        entry: file,
        dest: file.replace(distRegex, distFolder)
    };
});
```

**Comment by bahmutov** [comment]
yup, seems correct

**Comment by snuggs** [comment]
Nice @bahmutov @con-ssc 👍 this actually helps me with an issue I was having.

Many thanks!

Closing issue #14
