### ISSUE TITLE
Not possible to run "rollem -c"

### ISSUE THREAD

**Issue by YuryStrozhevsky** [bahmutov/rollem#19]
In fact the problem is in [this line](https://github.com/bahmutov/rollem/blob/master/bin/rollem.js#L9). Existing code must be replaced with this one:
```javascript
const configFilename = (argv.c === true) ? 'rollem.config.js' : argv.c;
```

**Comment by meszaros-lajos-gyorgy** [comment]
If you use the -c switch, then it expects another parameter after it, which would refer to the filename:
https://github.com/bahmutov/rollem#install-and-use
On it's own, the -c argument means nothing. It's there for you to tell rollem, that you are not happy with the default rollem.config.js and that you want to change that to your own.

We could add a proper error message saying, that the configuration is invalid.

For the record, this part throws the error: https://github.com/bahmutov/rollem/blob/master/bin/rollem.js#L11

argv.c is set, so it returns true.

Changing line 7 to this should "fix" the unexpected error:

```const argv = require('minimist')(process.argv.slice(2), {string: 'c'})```

**Comment by ghost** [comment]
I'm so curious about rollem

> You can pass -c <filename> to specify a different config file

it says, if filename is not exist, rollem is ought to find rollem.config.js(default name)

Because i use rollup.config.js for my project

Therefore, facts proved that  i am wrong

**Comment by YuryStrozhevsky** [comment]
@meszaros-lajos-gyorgy @liuliangsir In fact I am not interested in the fix for the issue anymore. I made [my own rollem](https://github.com/PeculiarVentures/rollem) and using it in all my projects. The story with the fix for main Rollem repo goes too long. Closing the issue.
