### ISSUE TITLE
Babel compatibility with rollem.config.js, import vs require

### ISSUE THREAD

**Issue by mariusk** [bahmutov/rollem#27]
I'm using rollup with rollem. In my `rollem.config.js`, when running `rollem --watch` as an npm script, if I import modules like this:

```
const nodeResolve = require('rollup-plugin-node-resolve');
const babel = require('rollup-plugin-babel');
const uglify = require('rollup-plugin-uglify');
```

everything works fine. If I do this instead however:

```
import babel from 'rollup-plugin-babel';
import nodeResolve from 'rollup-plugin-node-resolve';
import uglify from 'rollup-plugin-uglify';
```

everything still works, but now I get the following warnings:

```
'rollup-plugin-babel' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-node-resolve' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-uglify' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
```

As stated, everything works just fine (things get built), but it's still an annoying (and seemingly unecessary) warning.

**Comment by meszaros-lajos-gyorgy** [comment]
That warning is coming from rollup, not from rollem.

https://github.com/rollup/rollup/blob/master/src/Bundle.js#L360

**Comment by ghost** [comment]
@mariusk that message covered in the rollup docs. this should be closed

**Comment by mariusk** [comment]
@jhabdas I couldn't find where the rollup docs speaks about this. Link?

**Comment by ghost** [comment]
Sorry don't have a link. Know I saw it. Think it's in the section on CJS. If you can't find it on the site or Wiki, try searching their GH repo. Good luck!

**Comment by ghost** [comment]
I lied. Here's the link: https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

**Comment by mariusk** [comment]
Thank you for digging it out. My issue is related to running rollup and isn't related to what goes into the bundle, which your link seems to refer to I think. The underlying issue may be related though, no idea, but I never found an easy workaround. I had to stop using rollup at my end as it became too much work for a medium sized application (massaging third party dependencies in node_modules). Closing the ticket here should still be fine though as it does seem this is rollup related, not rollem.

**Comment by robdodson** [comment]
Yeah I'm also seeing this issue. Here's my `rollem.config.js`.

```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';

export default [{
  entry: 'src/inert.js',
  format: 'umd',
  dest: 'dist/inert.js',
  plugins: [
    resolve({jsnext: true, main: true}),
    commonjs(),
    babel({
      exclude: 'node_modules/**', // only transpile our source code
    }),
  ],
}, {
  entry: 'src/inert.js',
  format: 'umd',
  dest: 'dist/inert.min.js',
  plugins: [
    resolve({jsnext: true, main: true}),
    commonjs(),
    babel({
      exclude: 'node_modules/**', // only transpile our source code
    }),
    uglify(),
  ],
}];
```

The warnings I get are all related to the dependencies in `rollem.config.js`.

```
'rollup-plugin-node-resolve' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-commonjs' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-babel' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
'rollup-plugin-uglify' is imported by rollem.config.js, but could not be resolved – treating it as an external dependency
```

**Comment by nathancahill** [comment]
Also have this issue, trying out Rollem coming from Rollup. Exact same logs.

**Comment by nathancahill** [comment]
Looks like Rollem uses Rollup internally to read the config, so I'm guessing that it needs something like the node resolve plugin included there. I wasn't able to patch it in, I traced it, but it compiles `rollem.config.js` to cjs, and then `eval()`'s it. That gets pretty shaky for me, so I'm going to look for another option.

**Comment by nathancahill** [comment]
Here's my solution as a new build of Rollup CLI with support for multiple config objects like rollem.config.js: https://github.com/nathancahill/rollup-multiple

I also opened a PR on Rollup to add this functionality to core: https://github.com/rollup/rollup/pull/1389
