### ISSUE TITLE
Feature Request: Wildcard support?

### ISSUE THREAD

**Issue by objectkit** [bahmutov/rollem#39]
I could be missing something and Rollem already does what I'm looking for, but wildcards would be ideal in the context of building a module for unit testing where each export in a file within a directory is added to a CJS module...

```
gulp.task "build:module", ->
    rollEm [
       
        entry: "./src/main/js/example/app/**/*/.js"

        format: "cjs"
        dest: "./dist/app.js"
    ]
```

The wildcard entry ``./src/main/js/example/app/**/*/.js`` would prompt rollem to iterate the directory...

What do you think?

**Comment by meszaros-lajos-gyorgy** [comment]
You can use [rollup-plugin-multi-entry](https://github.com/rollup/rollup-plugin-multi-entry) for this purpose, rollem plays nice with it.

**Comment by objectkit** [comment]
Thanks for the feedback. Unfortunately issues with multi-entry prompted my request here. I'm presently looking for an alternative and rollem looked promising.

**Comment by meszaros-lajos-gyorgy** [comment]
Please take a look at the test config in our test folder to see how you can use rollup-plugin-multi-entry with rollem: https://github.com/bahmutov/rollem/blob/master/test/with-multi-entry-plugin/rollem.config.js

**Comment by objectkit** [comment]
Many thanks.
