### ISSUE TITLE
This is now part of rollup core

### ISSUE THREAD

**Issue by fregante** [bahmutov/rollem#44]
Rollup 0.42+ as per https://github.com/rollup/rollup/pull/1389

**Comment by ghost** [comment]
@bfred-it while the `rollup` CLI supports configuration arrays, the standard `rollup` API does not. Therefore, to get the convenience of the [rollem function](https://github.com/bahmutov/rollem/blob/master/src/index.js#L45), you would need to essentially re-implement that file within consumers of the `rollem` API.

Do you feel that should be the expectation imposed on `rollup` API consumers?

**Comment by fregante** [comment]
What's the advantage of feeding it an array vs running `for config of array, rollup(config)`?

**Comment by ghost** [comment]
How does that suggestion handle watching for file changes?

**Comment by fregante** [comment]
I don't think rollup' API supports file watching (but I think it should be added); it's only in the cli for now.

**Comment by ghost** [comment]
@bfred-it as you are already aware, I have filed https://github.com/rollup/rollup/issues/1460 to discuss how to make the Rollup interface a little easier to use so that we can swap out Rollem with Rollup.

**Comment by fregante** [comment]
Ha, I didn't even realize you were the same person, sorry 😅
