### ISSUE TITLE
Cannot generate IIFE or UMD bundles

### ISSUE THREAD

**Issue by atmin** [bahmutov/rollem#8]
```
Error: You must supply options.moduleName for UMD bundles
    at umd (/Users/aminev/dev/funponent/node_modules/rollem/node_modules/rollup/dist/rollup.js:6568:9)
    at Bundle.render (/Users/aminev/dev/funponent/node_modules/rollem/node_modules/rollup/dist/rollup.js:7452:16)
    at Object.write (/Users/aminev/dev/funponent/node_modules/rollem/node_modules/rollup/dist/rollup.js:7637:22)
    at /Users/aminev/dev/funponent/node_modules/rollem/src/index.js:11:21
```

**Comment by atmin** [comment]
https://github.com/bahmutov/rollem/pull/9

**Comment by snuggs** [comment]
Nicely done! @bahmutov !

**Comment by snuggs** [comment]
Where's the test for this @bahmutov? Or is that when you ask "Great question Snuggs. Where IS the test. You're the guy that knows all about testing..." #SeeWhatIDidThere?

**Comment by bahmutov** [comment]
where are any good tests that actually confirm the working code?

**Comment by snuggs** [comment]
Well the "test" IS the failure.  Should be able to reproduce the failure (possibly `catch`ing a `throw`. within an assertion. Your line of code would then make the test pass. Ran a code coverage analytic and we're pretty low. Maybe we should discuss in a new issue or offline as I feel we are waking zombies by starting a dialogue in a closed issue. :-) @bahmutov
